### ISSUE TITLE
upload step needs a git tag to work

### ISSUE THREAD

**Issue by stevebuik** [juxt/roll#12]
I could be recalling incorrectly but when I deployed from a repo that had no tags, the artifact build did not work. I forgot to record the error sorry.

From this I inferred that git tags drove the S3 artifact versioning. Apparently this is not the intention. Instead an explicit version from config should be used. I prefer this because it means git tags are free for other uses.

Maybe this explicit versioning should be in the sample config.edn instead of shelling out to git describe?

**Comment by jonpither** [comment]
This is actually a bug in Edge - not in Roll. Looking at options now.
